# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poshub.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_poshub_tool(object):
    def setupUi(self, poshub_tool):
        poshub_tool.setObjectName("poshub_tool")
        poshub_tool.resize(523, 918)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(poshub_tool.sizePolicy().hasHeightForWidth())
        poshub_tool.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        poshub_tool.setFont(font)
        poshub_tool.setLayoutDirection(QtCore.Qt.LeftToRight)
        poshub_tool.setIconSize(QtCore.QSize(50, 50))
        poshub_tool.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(poshub_tool)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_rtcm_server = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_rtcm_server.setGeometry(QtCore.QRect(10, 360, 501, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_rtcm_server.setFont(font)
        self.groupBox_rtcm_server.setObjectName("groupBox_rtcm_server")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_rtcm_server)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 491, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_rtcm_server = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_rtcm_server.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_rtcm_server.setObjectName("gridLayout_rtcm_server")
        self.lineEdit_rtcm_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_rtcm_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rtcm_name.setObjectName("lineEdit_rtcm_name")
        self.gridLayout_rtcm_server.addWidget(self.lineEdit_rtcm_name, 1, 1, 1, 1)
        self.pushButton_rtcm_read = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_rtcm_read.setFont(font)
        self.pushButton_rtcm_read.setObjectName("pushButton_rtcm_read")
        self.gridLayout_rtcm_server.addWidget(self.pushButton_rtcm_read, 2, 4, 1, 1)
        self.lineEdit_rtcm_pwd = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_rtcm_pwd.setFrame(True)
        self.lineEdit_rtcm_pwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_rtcm_pwd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rtcm_pwd.setObjectName("lineEdit_rtcm_pwd")
        self.gridLayout_rtcm_server.addWidget(self.lineEdit_rtcm_pwd, 1, 3, 1, 2)
        self.pushButton_rtcm_set = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_rtcm_set.setFont(font)
        self.pushButton_rtcm_set.setObjectName("pushButton_rtcm_set")
        self.gridLayout_rtcm_server.addWidget(self.pushButton_rtcm_set, 0, 4, 1, 1)
        self.lineEdit_rtcm_port = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_rtcm_port.setText("")
        self.lineEdit_rtcm_port.setMaxLength(6)
        self.lineEdit_rtcm_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rtcm_port.setObjectName("lineEdit_rtcm_port")
        self.gridLayout_rtcm_server.addWidget(self.lineEdit_rtcm_port, 0, 3, 1, 1)
        self.label_rtcm_state = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_rtcm_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rtcm_state.setObjectName("label_rtcm_state")
        self.gridLayout_rtcm_server.addWidget(self.label_rtcm_state, 2, 2, 1, 1)
        self.label_rtcm_ip = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_rtcm_ip.setObjectName("label_rtcm_ip")
        self.gridLayout_rtcm_server.addWidget(self.label_rtcm_ip, 0, 0, 1, 1)
        self.comboBox_rtcm_state = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_rtcm_state.setMaxCount(2)
        self.comboBox_rtcm_state.setObjectName("comboBox_rtcm_state")
        self.comboBox_rtcm_state.addItem("")
        self.comboBox_rtcm_state.addItem("")
        self.gridLayout_rtcm_server.addWidget(self.comboBox_rtcm_state, 2, 3, 1, 1)
        self.lineEdit_rtcm_ip = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_rtcm_ip.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_rtcm_ip.setText("")
        self.lineEdit_rtcm_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rtcm_ip.setObjectName("lineEdit_rtcm_ip")
        self.gridLayout_rtcm_server.addWidget(self.lineEdit_rtcm_ip, 0, 1, 1, 1)
        self.label_rtcm_point = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_rtcm_point.setObjectName("label_rtcm_point")
        self.gridLayout_rtcm_server.addWidget(self.label_rtcm_point, 2, 0, 1, 1)
        self.label_rtcm_name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_rtcm_name.setObjectName("label_rtcm_name")
        self.gridLayout_rtcm_server.addWidget(self.label_rtcm_name, 1, 0, 1, 1)
        self.label_rtcm_pwd = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_rtcm_pwd.setObjectName("label_rtcm_pwd")
        self.gridLayout_rtcm_server.addWidget(self.label_rtcm_pwd, 1, 2, 1, 1)
        self.label_rtcm_port = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_rtcm_port.setObjectName("label_rtcm_port")
        self.gridLayout_rtcm_server.addWidget(self.label_rtcm_port, 0, 2, 1, 1)
        self.comboBox_rtcm_point = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_rtcm_point.setObjectName("comboBox_rtcm_point")
        self.comboBox_rtcm_point.addItem("")
        self.comboBox_rtcm_point.addItem("")
        self.comboBox_rtcm_point.addItem("")
        self.comboBox_rtcm_point.addItem("")
        self.comboBox_rtcm_point.addItem("")
        self.gridLayout_rtcm_server.addWidget(self.comboBox_rtcm_point, 2, 1, 1, 1)
        self.groupBox_uart_cfg = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_uart_cfg.setGeometry(QtCore.QRect(10, 10, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_uart_cfg.setFont(font)
        self.groupBox_uart_cfg.setTitle("")
        self.groupBox_uart_cfg.setObjectName("groupBox_uart_cfg")
        self.label_port = QtWidgets.QLabel(self.groupBox_uart_cfg)
        self.label_port.setGeometry(QtCore.QRect(0, 10, 81, 28))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.label_port.setFont(font)
        self.label_port.setAlignment(QtCore.Qt.AlignCenter)
        self.label_port.setObjectName("label_port")
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox_uart_cfg)
        self.comboBox_port.setGeometry(QtCore.QRect(70, 10, 181, 23))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.comboBox_port.setFont(font)
        self.comboBox_port.setObjectName("comboBox_port")
        self.pushButton_scanport = QtWidgets.QPushButton(self.groupBox_uart_cfg)
        self.pushButton_scanport.setGeometry(QtCore.QRect(270, 10, 101, 28))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_scanport.setFont(font)
        self.pushButton_scanport.setStyleSheet("alternate-background-color: rgb(0, 255, 0);\n"
"alternate-background-color: rgb(225, 225, 225);")
        self.pushButton_scanport.setObjectName("pushButton_scanport")
        self.pushButton_ctrlport = QtWidgets.QPushButton(self.groupBox_uart_cfg)
        self.pushButton_ctrlport.setGeometry(QtCore.QRect(390, 10, 101, 28))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ctrlport.setFont(font)
        self.pushButton_ctrlport.setStyleSheet("alternate-background-color: rgb(0, 255, 0);\n"
"alternate-background-color: rgb(225, 225, 225);")
        self.pushButton_ctrlport.setObjectName("pushButton_ctrlport")
        self.groupBox_msg_server = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_msg_server.setGeometry(QtCore.QRect(10, 70, 501, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_msg_server.setFont(font)
        self.groupBox_msg_server.setObjectName("groupBox_msg_server")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_msg_server)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 491, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_msg_server = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_msg_server.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_msg_server.setObjectName("gridLayout_msg_server")
        self.pushButton_msg_set = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_msg_set.setFont(font)
        self.pushButton_msg_set.setObjectName("pushButton_msg_set")
        self.gridLayout_msg_server.addWidget(self.pushButton_msg_set, 0, 4, 1, 1)
        self.pushButton_msg_read = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_msg_read.setFont(font)
        self.pushButton_msg_read.setObjectName("pushButton_msg_read")
        self.gridLayout_msg_server.addWidget(self.pushButton_msg_read, 1, 4, 1, 1)
        self.lineEdit_msg_ip = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_msg_ip.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_msg_ip.setText("")
        self.lineEdit_msg_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_msg_ip.setObjectName("lineEdit_msg_ip")
        self.gridLayout_msg_server.addWidget(self.lineEdit_msg_ip, 0, 1, 1, 1)
        self.label_msg_ip = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_msg_ip.setFont(font)
        self.label_msg_ip.setObjectName("label_msg_ip")
        self.gridLayout_msg_server.addWidget(self.label_msg_ip, 0, 0, 1, 1)
        self.lineEdit_msg_port = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_msg_port.setText("")
        self.lineEdit_msg_port.setMaxLength(6)
        self.lineEdit_msg_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_msg_port.setObjectName("lineEdit_msg_port")
        self.gridLayout_msg_server.addWidget(self.lineEdit_msg_port, 0, 3, 1, 1)
        self.label_msg_port = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_msg_port.setObjectName("label_msg_port")
        self.gridLayout_msg_server.addWidget(self.label_msg_port, 0, 2, 1, 1)
        self.comboBox_msg_state = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_msg_state.setMaxCount(2)
        self.comboBox_msg_state.setObjectName("comboBox_msg_state")
        self.comboBox_msg_state.addItem("")
        self.comboBox_msg_state.addItem("")
        self.gridLayout_msg_server.addWidget(self.comboBox_msg_state, 1, 3, 1, 1)
        self.label_msg_state = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_msg_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msg_state.setObjectName("label_msg_state")
        self.gridLayout_msg_server.addWidget(self.label_msg_state, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 500, 501, 371))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 491, 81))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_mcu_ctrl = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_mcu_ctrl.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_mcu_ctrl.setObjectName("gridLayout_mcu_ctrl")
        self.pushButton_conn_usb = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_conn_usb.setObjectName("pushButton_conn_usb")
        self.gridLayout_mcu_ctrl.addWidget(self.pushButton_conn_usb, 0, 0, 1, 1)
        self.pushButton_close_usb = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_close_usb.setObjectName("pushButton_close_usb")
        self.gridLayout_mcu_ctrl.addWidget(self.pushButton_close_usb, 0, 1, 1, 1)
        self.pushButton_mk_disk = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_mk_disk.setObjectName("pushButton_mk_disk")
        self.gridLayout_mcu_ctrl.addWidget(self.pushButton_mk_disk, 0, 2, 1, 1)
        self.pushButton_read_mcu = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_read_mcu.setObjectName("pushButton_read_mcu")
        self.gridLayout_mcu_ctrl.addWidget(self.pushButton_read_mcu, 1, 0, 1, 1)
        self.pushButton_read_disk = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_read_disk.setObjectName("pushButton_read_disk")
        self.gridLayout_mcu_ctrl.addWidget(self.pushButton_read_disk, 1, 2, 1, 1)
        self.pushButton_clearn = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_clearn.setObjectName("pushButton_clearn")
        self.gridLayout_mcu_ctrl.addWidget(self.pushButton_clearn, 1, 1, 1, 1)
        self.textBrowser_logout = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_logout.setGeometry(QtCore.QRect(0, 90, 491, 271))
        self.textBrowser_logout.setObjectName("textBrowser_logout")
        self.groupBox_ota_server = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ota_server.setGeometry(QtCore.QRect(10, 180, 501, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_ota_server.setFont(font)
        self.groupBox_ota_server.setObjectName("groupBox_ota_server")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_ota_server)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 491, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_ota_server = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_ota_server.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ota_server.setObjectName("gridLayout_ota_server")
        self.pushButton_ota_set = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_ota_set.setFont(font)
        self.pushButton_ota_set.setObjectName("pushButton_ota_set")
        self.gridLayout_ota_server.addWidget(self.pushButton_ota_set, 0, 4, 1, 1)
        self.pushButton_ota_read = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_ota_read.setFont(font)
        self.pushButton_ota_read.setObjectName("pushButton_ota_read")
        self.gridLayout_ota_server.addWidget(self.pushButton_ota_read, 1, 4, 1, 1)
        self.lineEdit_ota_ip = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_ota_ip.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_ota_ip.setText("")
        self.lineEdit_ota_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ota_ip.setObjectName("lineEdit_ota_ip")
        self.gridLayout_ota_server.addWidget(self.lineEdit_ota_ip, 0, 1, 1, 1)
        self.label_ota_ip = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ota_ip.setFont(font)
        self.label_ota_ip.setObjectName("label_ota_ip")
        self.gridLayout_ota_server.addWidget(self.label_ota_ip, 0, 0, 1, 1)
        self.lineEdit_ota_port = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_ota_port.setText("")
        self.lineEdit_ota_port.setMaxLength(6)
        self.lineEdit_ota_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ota_port.setObjectName("lineEdit_ota_port")
        self.gridLayout_ota_server.addWidget(self.lineEdit_ota_port, 0, 3, 1, 1)
        self.label_ota_port = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_ota_port.setObjectName("label_ota_port")
        self.gridLayout_ota_server.addWidget(self.label_ota_port, 0, 2, 1, 1)
        self.comboBox_ota_state = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox_ota_state.setMaxCount(2)
        self.comboBox_ota_state.setObjectName("comboBox_ota_state")
        self.comboBox_ota_state.addItem("")
        self.comboBox_ota_state.addItem("")
        self.gridLayout_ota_server.addWidget(self.comboBox_ota_state, 1, 3, 1, 1)
        self.label_ota_state = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_ota_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ota_state.setObjectName("label_ota_state")
        self.gridLayout_ota_server.addWidget(self.label_ota_state, 1, 2, 1, 1)
        self.groupBox_OTA_updata = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_OTA_updata.setGeometry(QtCore.QRect(10, 290, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_OTA_updata.setFont(font)
        self.groupBox_OTA_updata.setObjectName("groupBox_OTA_updata")
        self.label_ota_type = QtWidgets.QLabel(self.groupBox_OTA_updata)
        self.label_ota_type.setGeometry(QtCore.QRect(-10, 20, 81, 28))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.label_ota_type.setFont(font)
        self.label_ota_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ota_type.setObjectName("label_ota_type")
        self.comboBox_ota_type = QtWidgets.QComboBox(self.groupBox_OTA_updata)
        self.comboBox_ota_type.setGeometry(QtCore.QRect(70, 20, 191, 23))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.comboBox_ota_type.setFont(font)
        self.comboBox_ota_type.setObjectName("comboBox_ota_type")
        self.comboBox_ota_type.addItem("")
        self.comboBox_ota_type.addItem("")
        self.comboBox_ota_type.addItem("")
        self.pushButton_ota_enable = QtWidgets.QPushButton(self.groupBox_OTA_updata)
        self.pushButton_ota_enable.setGeometry(QtCore.QRect(310, 20, 81, 28))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ota_enable.setFont(font)
        self.pushButton_ota_enable.setStyleSheet("alternate-background-color: rgb(0, 255, 0);\n"
"alternate-background-color: rgb(225, 225, 225);")
        self.pushButton_ota_enable.setObjectName("pushButton_ota_enable")
        poshub_tool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(poshub_tool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 26))
        self.menubar.setObjectName("menubar")
        poshub_tool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(poshub_tool)
        self.statusbar.setObjectName("statusbar")
        poshub_tool.setStatusBar(self.statusbar)
        self.actionabout = QtWidgets.QAction(poshub_tool)
        self.actionabout.setObjectName("actionabout")
        self.actionabout_2 = QtWidgets.QAction(poshub_tool)
        self.actionabout_2.setObjectName("actionabout_2")

        self.retranslateUi(poshub_tool)
        QtCore.QMetaObject.connectSlotsByName(poshub_tool)
        poshub_tool.setTabOrder(self.lineEdit_msg_ip, self.lineEdit_msg_port)
        poshub_tool.setTabOrder(self.lineEdit_msg_port, self.comboBox_msg_state)
        poshub_tool.setTabOrder(self.comboBox_msg_state, self.pushButton_msg_set)
        poshub_tool.setTabOrder(self.pushButton_msg_set, self.pushButton_msg_read)
        poshub_tool.setTabOrder(self.pushButton_msg_read, self.lineEdit_rtcm_ip)
        poshub_tool.setTabOrder(self.lineEdit_rtcm_ip, self.lineEdit_rtcm_port)
        poshub_tool.setTabOrder(self.lineEdit_rtcm_port, self.lineEdit_rtcm_name)
        poshub_tool.setTabOrder(self.lineEdit_rtcm_name, self.lineEdit_rtcm_pwd)
        poshub_tool.setTabOrder(self.lineEdit_rtcm_pwd, self.comboBox_rtcm_point)
        poshub_tool.setTabOrder(self.comboBox_rtcm_point, self.comboBox_rtcm_state)
        poshub_tool.setTabOrder(self.comboBox_rtcm_state, self.pushButton_rtcm_set)
        poshub_tool.setTabOrder(self.pushButton_rtcm_set, self.pushButton_rtcm_read)
        poshub_tool.setTabOrder(self.pushButton_rtcm_read, self.pushButton_conn_usb)
        poshub_tool.setTabOrder(self.pushButton_conn_usb, self.pushButton_close_usb)
        poshub_tool.setTabOrder(self.pushButton_close_usb, self.pushButton_mk_disk)
        poshub_tool.setTabOrder(self.pushButton_mk_disk, self.pushButton_read_mcu)

    def retranslateUi(self, poshub_tool):
        _translate = QtCore.QCoreApplication.translate
        poshub_tool.setWindowTitle(_translate("poshub_tool", "poshub_tool"))
        self.groupBox_rtcm_server.setTitle(_translate("poshub_tool", "RTCM服务器"))
        self.pushButton_rtcm_read.setText(_translate("poshub_tool", "读取"))
        self.pushButton_rtcm_set.setText(_translate("poshub_tool", "设置"))
        self.label_rtcm_state.setText(_translate("poshub_tool", "状态"))
        self.label_rtcm_ip.setText(_translate("poshub_tool", "IP地址"))
        self.comboBox_rtcm_state.setItemText(0, _translate("poshub_tool", "OFF"))
        self.comboBox_rtcm_state.setItemText(1, _translate("poshub_tool", "ON"))
        self.label_rtcm_point.setText(_translate("poshub_tool", "接入点"))
        self.label_rtcm_name.setText(_translate("poshub_tool", "用户名"))
        self.label_rtcm_pwd.setText(_translate("poshub_tool", "密码"))
        self.label_rtcm_port.setText(_translate("poshub_tool", "端口"))
        self.comboBox_rtcm_point.setItemText(0, _translate("poshub_tool", "RTCM32_GGB"))
        self.comboBox_rtcm_point.setItemText(1, _translate("poshub_tool", "BJJZ1"))
        self.comboBox_rtcm_point.setItemText(2, _translate("poshub_tool", "GUDN1"))
        self.comboBox_rtcm_point.setItemText(3, _translate("poshub_tool", "RTCM30_GG"))
        self.comboBox_rtcm_point.setItemText(4, _translate("poshub_tool", "AUTO"))
        self.label_port.setText(_translate("poshub_tool", "端口号"))
        self.pushButton_scanport.setText(_translate("poshub_tool", "扫描串口"))
        self.pushButton_ctrlport.setText(_translate("poshub_tool", "打开串口"))
        self.groupBox_msg_server.setTitle(_translate("poshub_tool", "MSG服务器"))
        self.pushButton_msg_set.setText(_translate("poshub_tool", "设置"))
        self.pushButton_msg_read.setText(_translate("poshub_tool", "读取"))
        self.label_msg_ip.setText(_translate("poshub_tool", "IP地址"))
        self.label_msg_port.setText(_translate("poshub_tool", "端口"))
        self.comboBox_msg_state.setItemText(0, _translate("poshub_tool", "OFF"))
        self.comboBox_msg_state.setItemText(1, _translate("poshub_tool", "ON"))
        self.label_msg_state.setText(_translate("poshub_tool", "状态"))
        self.pushButton_conn_usb.setText(_translate("poshub_tool", "连接USB"))
        self.pushButton_close_usb.setText(_translate("poshub_tool", "断开USB"))
        self.pushButton_mk_disk.setText(_translate("poshub_tool", "设备格式化"))
        self.pushButton_read_mcu.setText(_translate("poshub_tool", "读取设备信息"))
        self.pushButton_read_disk.setText(_translate("poshub_tool", "设备容量"))
        self.pushButton_clearn.setText(_translate("poshub_tool", "清除输出"))
        self.groupBox_ota_server.setTitle(_translate("poshub_tool", "OTA服务器"))
        self.pushButton_ota_set.setText(_translate("poshub_tool", "设置"))
        self.pushButton_ota_read.setText(_translate("poshub_tool", "读取"))
        self.label_ota_ip.setText(_translate("poshub_tool", "IP地址"))
        self.label_ota_port.setText(_translate("poshub_tool", "端口"))
        self.comboBox_ota_state.setItemText(0, _translate("poshub_tool", "OFF"))
        self.comboBox_ota_state.setItemText(1, _translate("poshub_tool", "ON"))
        self.label_ota_state.setText(_translate("poshub_tool", "状态"))
        self.groupBox_OTA_updata.setTitle(_translate("poshub_tool", "OTA升级"))
        self.label_ota_type.setText(_translate("poshub_tool", "类型"))
        self.comboBox_ota_type.setItemText(0, _translate("poshub_tool", "LaneTo"))
        self.comboBox_ota_type.setItemText(1, _translate("poshub_tool", "Poshub"))
        self.comboBox_ota_type.setItemText(2, _translate("poshub_tool", "LaneTo and Poshub"))
        self.pushButton_ota_enable.setText(_translate("poshub_tool", "设置"))
        self.actionabout.setText(_translate("poshub_tool", "about"))
        self.actionabout_2.setText(_translate("poshub_tool", "about"))
